# -g is for debug info
CFLAGS=-Wall -g

all: ex1 ex3 ex9 ex10 ex16 database_ex17

p_func_ex18: p_func_ex18.c output.c output.h
	gcc p_func_ex18.c output.c -o p_func_ex18

clean:
	rm -f ex1 ex3 ex9 ex10 ex16 database_ex17 debug test ex18; rm -rf *.dSYM
